language: c

sudo: false

addons:
  apt:
    packages:
      - libpciaccess-dev

script:
  - git submodule update --init
  - ./buildrump.sh/buildrump.sh -T rumptools -s rumpsrc -V NOSTATICLIB=1 -qq -j16 checkout fullbuild
  - (cd src-linux-uio ; ../rumptools/rumpmake -j16 dependall && ../rumptools/rumpmake install)
  - (cd examples ; ../rumptools/rumpmake -j16 dependall)

notifications:
  irc:
    channels:
      - "chat.freenode.net#rumpkernel-builds"
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'
    skip_join: true
    use_notice: true
  email:
    recipients:
      - rumpkernel-builds@freelists.org
    on_success: always
    on_failure: always
